name: 'Do AutoPR'
description: 'A composite GitHub action that automatically stages and commits code & creates and approves PRs'
inputs:
  message:  # id of input
    description: 'the commit message, the PR title & description'
    required: true
    default: 'updates'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
