name: 'Do AutoPR'
description: 'A composite GitHub action that automatically stages and commits code & creates and approves PRs'
inputs:
  message:  # id of input
    description: 'the commit message, the PR title & description'
    required: true
    default: 'updates'
runs:
  using: "composite"
  steps:
    - run: git add .
      shell: bash
    - run: git branch -M feature-branch
      shell: bash
    - run: git commit -m ${{ inputs.message }}
      shell: bash
    - run: git push origin feature-branch
      shell: bash
    - run: gh pr create --title ${{ inputs.message }} --body ${{ inputs.message }} 
      shell: bash
    - run: sleep 1 
      shell: bash
    - run: gh pr merge feature-branch --merge 
      shell: bash
    - run: git checkout main
      shell: bash
    - run: git branch -D feature-branch || echo 'Feature branch already deleted'
      shell: bash
